apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: olanrewajuajayi2003@gmail.com
    privateKeySecretRef:
      name: letsencrypt-secret-key
    solvers:
    - http01:
        ingress:
          class: istio
